### PR TITLE
Find documents by id using pattern

### PR DESCRIPTION
**Pull request by tomidery**
Allow searching document by `id` using SQL `LIKE` pattern

### CODE REVIEW

**Comment by h3rald** [comment]
Uhm... simple enough I must say, and it could be useful as well.

Merged, thanks!

**Comment by tomidery** [comment]
Hi Fabio,
Thanks for accepting my PRs. The next one is more complex. I tried to find
a way to integrate the new functionality into LiteStore without changing
too much code. I still needed a hook to be called when .htm document was
requested and not found. I didn't want to use middleware for that because
then I need to write js code. I was thinking about making kind of generic
callback mechanism which could be implemented by some extensions (like my
renderer.nim) but I wasn't sure how to do that. Any suggestions welcomed.
Kind regards,
Piotr

**Comment by h3rald** [comment]
I am afraid the best way to do that is indeed via middleware. If I added a hook like that I would have to add it for other situations as well -- honestly, that's what middleware is for: to create slightly more custom behaviors.

Otherwise just fork, it would be easier I think than introducing another general-purpose (or worse, specialized) customization method.

Thank you for all your PRs anyway!

**Comment by tomidery** [comment]
In object oriented world I could add a class inheriting from the litestore
and then perform my required job there. It may be as easy as changing proc
to method...

**Pull request merged**
